### ISSUE TITLE
Theme not installing/working via package control

### ISSUE THREAD

**Issue by daynaskully** [jrolfs/sodarized#12]
I had this installed and working fine via packagecontrol, wanted to modify the tabs; ended up uninstalling via package control and re-installing; except the re-install never worked.

Updated latest ST3 build, tried again; not applying (it's downloading fine into "installed packages"). No menu option for the theme. Tried editing preferences as noted in the readme to include "theme". Doesn't apply even after a restart.

Shows up fine as an installed package. I can add/remove it via package control but it will never activate regardless of whats in my preferences file.

**Comment by jrolfs** [comment]
Did you end up getting this working? I've been using Neovim for the past 2 years now so I've had less time to maintain this project. If you're still having trouble installing from Package Control I could try and publish a new version.
