### ISSUE TITLE
Input fields are not styled in Sodarized Light 3 

### ISSUE THREAD

**Issue by engamaraziz** [jrolfs/sodarized#2]
![screen shot 2013-09-20 at 12 18 31 am](https://f.cloud.github.com/assets/4993765/1178366/c43344da-21ab-11e3-8854-2784c8d92bd3.png)

![screen shot 2013-09-20 at 12 19 33 am](https://f.cloud.github.com/assets/4993765/1178380/f88937e4-21ab-11e3-9436-a164f4a74763.png)

Please note that when having `"theme": "Sodarized Light.sublime-theme"` the fields shows as styled but I believe I am supposed to use `Sodarized Light 3.sublime-theme` with Sublime 3.

Also note that I tried to restart Sublime several times and that didn't help.

**Comment by jrolfs** [comment]
Looks like I missed a file when I renamed the theme and settings files to "Sodarized". Fixed in https://github.com/jrolfs/sodarized/commit/8cc273e04b1ddcc9f5458e6593963c62f79e0774 and published in [0.5.5](https://github.com/jrolfs/sodarized/releases/tag/0.5.5).
