### ISSUE TITLE
Dark theme – Project Prompt background color

### ISSUE THREAD

**Issue by niklas-r** [jrolfs/sodarized#3]
Background color seems to be the same as in the original Soda Dark theme.

ST Build 3047

![image](http://i.imgur.com/rogGYJT.jpg)

**Comment by jrolfs** [comment]
I did not even know about this feature. Looking into it.

**Comment by jrolfs** [comment]
This should be fixed now, not sure if I'm entirely happy with the color yet.

**Comment by jrolfs** [comment]
@niklas-r
