### ISSUE TITLE
Spacing around tab arrows looks off

### ISSUE THREAD

**Issue by ericmatthys** [jrolfs/sodarized#4]
![screen shot 2014-06-25 at 10 37 45 am](https://cloud.githubusercontent.com/assets/1154586/3388352/0ef60514-fc87-11e3-899d-8f79e6dcb88f.png)

**Comment by jrolfs** [comment]
Can you still reproduce this in the most recent build of ST3?

**Comment by jrolfs** [comment]
:grimacing:

**Comment by ericmatthys** [comment]
Looks better now.
