### ISSUE TITLE
Sublime Text update on August 27 2014 adds sidebar icons beside Sodarized icons

### ISSUE THREAD

**Issue by adlersantos** [jrolfs/sodarized#5]
![sidebar](https://cloud.githubusercontent.com/assets/1208372/4092105/3d85e256-2f8f-11e4-9c89-e02c82e0ca56.png)

Maybe we can have an option to toggle the sodarized icons on or off?

**Comment by jrolfs** [comment]
I just upgraded and noticed this, I'll see what I can do. Are you referring to the new folder icons (with the black outlines).

**Comment by adlersantos** [comment]
Yup, it's the one with the black outlines. Thanks for looking into it!

**Comment by jrolfs** [comment]
So I took a look and didn't see any new setting for toggling the new icons that were added. I did however take a peak into the default theme and it has new assets for these icons. I didn't really see an easy way of hiding them for now so I'm just going to have to modify the new icon assets to match the Solarized color scheme and put out a new release.

**Comment by mvhenderson** [comment]
FYI: I've removed the icons completely based on this [forum post](http://www.sublimetext.com/forum/viewtopic.php?f=2&t=16719&start=20#p62992)

Create file `.../Sublime Text 3/Packages/User/Sodarized Dark 3/Sodarized Dark 3.sublime-theme` with the following content:

``` json
[
   {
       "class": "icon_file_type",
       "content_margin": [0,0]
   },
   {
       "class": "icon_folder",
       "content_margin": [0,0]
   },
   {
       "class": "icon_folder_loading",
       "content_margin": [0,0]
   }
]
```

And the result:
![sidebar](https://cloud.githubusercontent.com/assets/669176/4129513/d83aec16-3321-11e4-80a9-1aed993fc808.png)

**Comment by jrolfs** [comment]
Aha! I figured eliminating the margin would still leave a considerable gap but that doesn't look too bad. If I can't manage to make the icons look decent with Sodarized this will probably be the way to go.

**Comment by jrolfs** [comment]
For anyone looking to hide the icons for now, you can pull the theme directly from https://github.com/jrolfs/sodarized/pull/6

**Comment by adlersantos** [comment]
Thanks a lot for this!

**Comment by jrolfs** [comment]
Anyone in favor of keeping the new icons? I'm leaning towards just merging https://github.com/jrolfs/sodarized/pull/6

Thanks for the tip @mvhenderson, assuming you are in support :flushed:

**Comment by mvhenderson** [comment]
Not in support, just like a clean coding environment! 

I have no preference. How much effort would it be to support the new icons? Seems that would be the best path since they are now standard theme elements and those of us who don't want them can just use my config tweak.

**Comment by jrolfs** [comment]
@mvhenderson that's a pretty good point. I'll play with the icons a bit when I have a chance.

**Comment by henrebotha** [comment]
Is anyone still maintaining this project? I just started using it now - so pretty! - but would like to see this issue resolved.

**Comment by jrolfs** [comment]
Going with #7 for now.

**Comment by jrolfs** [comment]
I'll publish a release soon.

**Comment by jrolfs** [comment]
@henrebotha I published a release. I've been using [Material Theme](https://github.com/equinusocio/material-theme) so maybe I'll port those icons over to this one. Orrr I might create a Solarized variant of that theme ;)

**Comment by henrebotha** [comment]
Ah, cheers mate!
